### ISSUE TITLE
[TODO] Improve form controls

### ISSUE THREAD

**Issue by samuelgrant** [ssm-deepcove/deepcove-website#13]
Imporve the method of setting the type and auto complete for form controls.

- [x] Create a constant for AutoComplete
- [x] Create a constant for Type 
- [x] Write documentation for [Input/TextArea](https://github.com/ssm-deepcove/deepcove-website/wiki/React-Form-Controls)

Example:
```JS
constant InputTypes = ["email", "file". "password", "text"] // etc
```

Inside of the following form control classes use a condition to display the prop if one of the constant arrays contains the value. Work out a good way to handle the prop if it does not.
