### ISSUE TITLE
[TODO] Exception Emails

### ISSUE THREAD

**Issue by samuelgrant** [ssm-deepcove/deepcove-website#14]
Let's implement exception emails to a developers group. In the email include:
- [x] User name || guest
- [x] Users IP address
- [ ] AJAX or regular
- [x] Date/Time UTC
- [x] StackTrace

Let's also consider using a queue to send these emails

**Comment by samuelgrant** [comment]
Most of this is done, I just need to work out how to get a list of EmaiContacts. I thought the obvious solution was to get a list of users that were in a group with a particular name, but I can't seem tomake that work

```CS
new EmailContact {
    Address = "example@example.com",
    Name = "user name"
}
```

cc @jacksos101

**Comment by samuelgrant** [comment]
For record purposes:

- I have an interface, email template and model for this. 
- I need to complete a database query (see above) that gets a list of Developers and foreaches this so we can send it out
- TODO: Once I send the first email, work on cleaning the view up to remove info we don't need.

**Comment by samuelgrant** [comment]
This is done.
